import type { Metadata } from "next";
import { Anuphan } from 'next/font/google';
import '@/assets/styles/app.scss'

const anuphan = Anuphan({
  subsets: ['latin'],
  variable: '--font-anuphan',
});

export const metadata: Metadata = {
  title: "Decentralab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${anuphan.variable}`}>
        {children}
      </body>
    </html>
  );
}
